import type { TerritoryProfile } from "../types";
import { createPanelProfile } from "./fixtures";

const urbanDenseBase = createPanelProfile("urbanDense");

/** Rennes (35238) — profil de référence grande ville pour tests de pertinence contextuelle. */
export const rennesLikeProfile: TerritoryProfile = {
  ...urbanDenseBase,
  name: "Rennes",
  inseeCode: "35238",
  postalCodes: ["35000"],
  department: { code: "35", name: "Ille-et-Vilaine" },
  region: { code: "53", name: "Bretagne" },
  epci: { code: "243500139", name: "Rennes Métropole" },
  population: 225_081,
  densityPerKm2: 4_200,
  enrichment: {
    ...urbanDenseBase.enrichment!,
    equipments: {
      year: 2024,
      totalEquipments: 1_850,
      byDomain: [{ code: "D", label: "Santé", count: 120 }],
      byType: [{ code: "D201", label: "Médecin généraliste", count: 85 }],
      transport: { totalEquipments: 12, byType: [], available: true, note: "" },
      available: true,
      note: "",
      domainBreakdownLabel: "Domaines",
      topTypesLabel: "Types",
      qualitativeSummary: "Offre d'équipements dense.",
      domainCountsAreTypeCounts: false,
    },
    employmentSectors: {
      year: 2024,
      totalEstablishments: 12_000,
      totalSalariedPosts: 95_000,
      sectors: [
        {
          code: "OQ",
          label: "Administration publique, enseignement, santé",
          establishments: 800,
          salariedPosts: 28_000,
        },
        {
          code: "MN",
          label: "Activités spécialisées, scientifiques et techniques",
          establishments: 1_200,
          salariedPosts: 15_000,
        },
      ],
      available: true,
      note: "",
    },
    proximityServices: {
      year: 2025,
      franceServicesCount: 1,
      structureLabels: ["France Services Rennes"],
      available: true,
      note: "",
    },
    mobility: {
      irve: {
        year: 2024,
        chargingPoints: 48,
        stations: 16,
        available: true,
        note: "",
      },
      commute: {
        year: 2022,
        employedCount: 95_000,
        carSharePercent: 52.4,
        publicTransportSharePercent: 22.1,
        available: true,
        note: "",
      },
      connectivity: {
        vintage: "2025_T4",
        fiberEligibleSharePercent: 98.2,
        totalPremises: 122_000,
        fiberEligiblePremises: 120_000,
        technologies: ["Fibre", "Cuivre"],
        available: true,
        note: "",
      },
    },
    tourism: {
      year: 2025,
      accommodationPlaces: 3_819,
      available: true,
      note: "",
    },
    enterprises: {
      legalUnitsWithEstablishment: 18_500,
      legalUnitsIsCapped: false,
      essCount: 7_873,
      rgeCount: 130,
      inseeLegalUnits: 12_400,
      inseeEstablishments: 14_200,
      inseeSideYear: 2022,
      millesime: "2022",
      divergenceWarning: null,
      note: "",
    },
    security: {
      year: 2024,
      indicators: [
        {
          id: "vols",
          label: "Vols sans violence",
          count: 2_400,
          ratePer1000: 10.7,
          departmentRatePer1000: 7.2,
          diffused: true,
        },
        {
          id: "cambriolages",
          label: "Cambriolages",
          count: 680,
          ratePer1000: 3.0,
          departmentRatePer1000: 2.1,
          diffused: true,
        },
      ],
      diffusedIndicatorCount: 8,
      available: true,
      note: "",
    },
    territoryTypology: {
      comparisonProfile: "metropole",
      summaryLabel: "commune dense de grande agglomération",
      availableFamilies: ["density_grid", "attraction_area"],
      missingFamilies: [],
      densityGrid: {
        available: true,
        levelCode: "1",
        levelLabel: "Très dense",
        simplifiedLabel: "commune très dense",
        source: "INSEE",
        vintage: 2024,
        note: "",
      },
      attractionArea: {
        available: true,
        categoryCode: "1",
        categoryLabel: "Pôle principal",
        role: "pole",
        source: "INSEE",
        vintage: 2020,
        note: "",
      },
      urbanUnit: {
        available: true,
        unitCode: "35238",
        unitLabel: "Rennes",
        belongsToUrbanUnit: true,
        role: "ville_centre",
        sizeClass: "1",
        source: "INSEE",
        vintage: 2020,
        note: "",
      },
      publicPolicyTypologies: {
        available: true,
        petitesVillesDeDemain: false,
        actionCoeurDeVille: false,
        franceRuralitesRevitalisation: false,
        franceRuralitesRevitalisationPlus: false,
        villagesAvenir: false,
        source: "ANCT",
        vintage: 2024,
        note: "",
      },
    },
  },
};

const periurbanBase = createPanelProfile("periurban");

/** Bousse (57190) — petite commune, SSMSI partiel, prudence petits effectifs. */
export const bousseLikeProfile: TerritoryProfile = {
  ...periurbanBase,
  name: "Bousse",
  inseeCode: "57190",
  postalCodes: ["57310"],
  department: { code: "57", name: "Moselle" },
  region: { code: "44", name: "Grand Est" },
  population: 2_812,
  densityPerKm2: 420,
  enrichment: {
    ...periurbanBase.enrichment!,
    security: {
      year: 2024,
      indicators: [
        {
          id: "vols",
          label: "Vols sans violence",
          count: 12,
          ratePer1000: 4.3,
          departmentRatePer1000: 3.1,
          diffused: true,
        },
        {
          id: "cambriolages",
          label: "Cambriolages",
          count: 3,
          ratePer1000: 1.1,
          departmentRatePer1000: 0.7,
          diffused: true,
        },
        {
          id: "incivilites",
          label: "Incivilités",
          count: 8,
          ratePer1000: 2.8,
          departmentRatePer1000: 2.0,
          diffused: true,
        },
      ],
      diffusedIndicatorCount: 4,
      available: true,
      note: "Diffusion partielle SSMSI.",
    },
    enterprises: {
      legalUnitsWithEstablishment: 120,
      legalUnitsIsCapped: false,
      essCount: 18,
      rgeCount: 4,
      inseeLegalUnits: 110,
      inseeEstablishments: 130,
      inseeSideYear: 2022,
      millesime: "2022",
      divergenceWarning: null,
      note: "",
    },
    risks: periurbanBase.enrichment!.risks,
    derived: {
      populationGrowthPercent: 12.4,
      populationGrowthFromYear: 2010,
      populationGrowthToYear: 2022,
      irvePointsPer1000Residents: null,
      socialHousingVacancyRatePercent: null,
      equipmentsPer1000Residents: null,
      lovacRpVacancySpreadPercent: null,
      realEstatePremiumRatio: null,
      available: true,
      note: "",
    },
    geography: {
      attractionArea: periurbanBase.enrichment!.geography?.attractionArea ?? null,
      epciComparison: {
        available: true,
        epciName: "Communauté de communes du Bassin de Boulay",
        communeCount: 12,
        communeRankByPopulation: 2,
        communeRankByDensity: 3,
        epciAveragePopulation: 1800,
        epciAverageDensity: 95,
        note: "",
      },
    },
    territoryTypology: {
      comparisonProfile: "petite_centralite",
      summaryLabel: "petite centralité",
      availableFamilies: ["density_grid"],
      missingFamilies: [],
      densityGrid: {
        available: true,
        levelCode: "3",
        levelLabel: "Intermédiaire",
        simplifiedLabel: "commune de densité intermédiaire",
        source: "INSEE",
        vintage: 2024,
        note: "",
      },
    },
  },
};
