import type { TerritoryProfile, TerritoryEnrichment } from "../types";

function baseEnrichment(overrides: Partial<TerritoryEnrichment> = {}): TerritoryEnrichment {
  return {
    populationHistory: null,
    sociodemographics: null,
    enterprises: null,
    employmentSectors: null,
    equipments: null,
    education: null,
    health: null,
    risks: null,
    security: null,
    housing: null,
    mobility: null,
    urbanPolicy: null,
    fiscal: null,
    publicAccounts: null,
    proximityServices: null,
    tourism: null,
    geography: null,
    property: null,
    derived: null,
    sources: [],
    ...overrides,
  };
}

/** Saint-Girons (09225) — cas de régression démographie / vieillissement / SIDE. */
export const saintGironsProfile: TerritoryProfile = {
  name: "Saint-Girons",
  inseeCode: "09225",
  postalCodes: ["09200"],
  department: { code: "09", name: "Ariège" },
  region: { code: "76", name: "Occitanie" },
  epci: { code: "200027183", name: "CC Couserans Pyrenées" },
  population: 6_008,
  densityPerKm2: 280,
  coordinates: { latitude: 42.984, longitude: 1.145 },
  surfaceKm2: 21.5,
  sources: [],
  enrichment: baseEnrichment({
    populationHistory: {
      latestYear: 2022,
      latestPopulation: 6_008,
      history: [
        { year: 2010, population: 6_371 },
        { year: 2022, population: 6_008 },
      ],
      available: true,
      note: "",
    },
    sociodemographics: {
      year: 2021,
      ageBands: [
        { label: "60-74 ans", population: 1_111, sharePercent: 18.5 },
        { label: "75-89 ans", population: 727, sharePercent: 12.1 },
        { label: "90 ans ou plus", population: 45, sharePercent: 7.5 },
      ],
      unemploymentRate: 11.2,
      medianDisposableIncome: 19_500,
      available: true,
      note: "RP 2021",
    },
    derived: {
      populationGrowthPercent: -5.7,
      populationGrowthFromYear: 2010,
      populationGrowthToYear: 2022,
      irvePointsPer1000Residents: null,
      socialHousingVacancyRatePercent: null,
      equipmentsPer1000Residents: null,
      available: true,
      note: "",
    },
    enterprises: {
      legalUnitsWithEstablishment: 710,
      legalUnitsIsCapped: false,
      essCount: 289,
      rgeCount: 12,
      inseeLegalUnits: 658,
      inseeEstablishments: 749,
      inseeSideYear: 2022,
      millesime: "2022",
      divergenceWarning: null,
      note: "",
    },
    employmentSectors: {
      year: 2022,
      totalEstablishments: 620,
      totalSalariedPosts: 4_200,
      sectors: [
        { code: "GZ", label: "Commerce", establishments: 120, salariedPosts: 800 },
        { code: "KQ", label: "Santé humaine", establishments: 45, salariedPosts: 650 },
        { code: "OQ", label: "Administration publique", establishments: 30, salariedPosts: 500 },
      ],
      available: true,
      note: "FLORES A17 ; pas d'analyse d'évolution.",
    },
    equipments: {
      year: 2024,
      totalEquipments: 515,
      byDomain: [
        { code: "A", label: "Services pour les particuliers", count: 12 },
        { code: "B", label: "Commerces", count: 8 },
        { code: "D", label: "Santé et action sociale", count: 6 },
      ],
      byType: [],
      transport: {
        totalEquipments: 4,
        byType: [{ code: "E101", label: "Taxis-VTC", count: 4 }],
        available: true,
        note: "",
      },
      available: true,
      note: "",
      domainBreakdownLabel: "Types par domaine",
      topTypesLabel: "Top types",
      qualitativeSummary:
        "515 équipements recensés, avec une diversité de services de proximité, commerces et santé.",
      domainCountsAreTypeCounts: true,
    },
    housing: {
      year: 2021,
      totalUnits: 0,
      occupiedUnits: 0,
      vacantUnits: 0,
      totalDwellings: 3_500,
      rpVacantDwellings: 658,
      rpVacancyRatePercent: 18.8,
      socialHousingSharePercent: 0,
      vacancyRatePercent: null,
      available: true,
      note: "RPLS + RP logement",
    },
    mobility: {
      irve: {
        year: 2024,
        chargingPoints: 6,
        stations: 2,
        available: true,
        note: "",
      },
      commute: {
        year: 2021,
        employedCount: 2_400,
        carSharePercent: 69.3,
        publicTransportSharePercent: 0.8,
        available: true,
        note: "",
      },
      connectivity: {
        vintage: "2025_T4",
        fiberEligibleSharePercent: 72.5,
        totalPremises: 3_200,
        fiberEligiblePremises: 2_320,
        technologies: ["Fibre", "Cuivre"],
        available: true,
        note: "Estimation IPE ARCEP",
      },
    },
    health: {
      year: 2024,
      totalEstablishments: 12,
      totalCapacity: null,
      byCategory: [{ code: "1", label: "Établissements sanitaires", count: 3 }],
      byType: [{ code: "101", label: "Centres de santé", count: 2 }],
      available: true,
      note: "",
    },
    education: {
      year: 2024,
      totalOpen: 5,
      byType: [{ code: "E", label: "École", count: 4 }],
      bySector: [
        { code: "PU", label: "Public", count: 4 },
        { code: "PR", label: "Privé", count: 1 },
      ],
      byLevel: [{ code: "1", label: "Élémentaire", count: 3 }],
      available: true,
      note: "",
    },
    security: {
      year: 2024,
      indicators: [
        {
          id: "violences",
          label: "Violences physiques",
          count: 45,
          ratePer1000: 7.5,
          departmentRatePer1000: 5.2,
          diffused: true,
        },
      ],
      diffusedIndicatorCount: 1,
      available: true,
      note: "",
    },
    risks: {
      radon: null,
      flood: { zones: ["Zone A"], count: 1 },
      catNatEvents: [
        { label: "Inondation et/ou Coulées de boue", startDate: "2018-06-01" },
        { label: "Inondation et/ou Coulées de boue", startDate: "2020-10-12" },
      ],
      available: true,
      note: "",
    },
    tourism: {
      year: 2025,
      accommodationPlaces: 75,
      available: true,
      note: "Sans fréquentation",
    },
    property: {
      year: 2024,
      averagePricePerM2: 1_429,
      averageTransactionPrice: 165_000,
      mutationCount: 114,
      houseMutations: 80,
      apartmentMutations: 34,
      houseSharePercent: null,
      apartmentSharePercent: null,
      priceHistory: [],
      departmentCode: "09",
      departmentAveragePricePerM2: 1_300,
      available: true,
      note: "",
    },
    geography: {
      attractionArea: {
        code: "091",
        label: "Saint-Girons",
        categoryCode: "4",
        categoryLabel: "Commune-centre d'aire d'attraction",
        available: true,
        note: "",
      },
      epciComparison: {
        epciName: "CC Couserans Pyrenées",
        communeCount: 27,
        communeRankByPopulation: 1,
        communeRankByDensity: 2,
        epciAveragePopulation: 1_100,
        epciAverageDensity: 35,
        available: true,
        note: "",
      },
    },
    urbanPolicy: {
      year: 2024,
      hasQpv: false,
      qpvCount: 0,
      qpvLabels: [],
      available: true,
      note: "",
    },
  }),
};

export const ruralProfileMinimal: TerritoryProfile = {
  name: "Commune rurale",
  inseeCode: "01001",
  postalCodes: ["01000"],
  department: { code: "01", name: "Ain" },
  region: { code: "84", name: "Auvergne-Rhône-Alpes" },
  epci: null,
  population: 800,
  densityPerKm2: 25,
  coordinates: null,
  surfaceKm2: 32,
  sources: [],
  enrichment: null,
};
