/** Réexporte la qualification socio-économique depuis la couche centrale. */
export {
  buildIncomeWatchPointSentence,
  countSocioEconomicFragilitySignals,
  DEBT_PER_CAPITA_WATCH_POINT_THRESHOLD_EUR,
  isDescriptiveIncomeWatchPointSentence,
  isEligibleEmploymentWatchPoint,
  isEligibleFinancesWatchPoint,
  isEligibleIncomeWatchPoint,
  isEligibleSocioEconomicWatchPoint,
  MEDIAN_INCOME_LOW_WATCH_POINT_THRESHOLD_EUR,
  MEDIAN_INCOME_MODERATE_WATCH_POINT_THRESHOLD_EUR,
  qualifiesAsDebtWatchPoint,
  qualifiesAsIncomeWatchPoint,
  qualifiesAsLowMedianIncomeForWatchPoint,
  qualifiesAsUnemploymentWatchPoint,
  UNEMPLOYMENT_WATCH_POINT_THRESHOLD_PERCENT,
  usesCompositeIncomeWatchPointRationale,
  VACANCY_FRAGILITY_THRESHOLD_PERCENT,
} from "./qualify-facts";
